include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    depend_on_referenced_packages: ignore
    deprecated_member_use: ignore
    invalid_use_of_visible_for_testing_member: ignore
    use_build_context_synchronously: ignore
