name: time_of_mine
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  flutter_bloc: ^9.1.1
  table_calendar: ^3.2.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  http: ^1.5.0
  flutter_dotenv: ^6.0.0
  flutter_localisation: ^2.0.0
  intl: ^0.20.2
  auto_size_text: ^3.0.0
  collection: ^1.19.1
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 24

flutter:
  assets:
    - .env
  uses-material-design: true
  generate: true