// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFv3N0lybkZdlIH6XgXbJTo_qTrP_uRxk',
    appId: '1:1038026278537:web:56c23b432634ce85336858',
    messagingSenderId: '1038026278537',
    projectId: 'time-of-mine',
    authDomain: 'time-of-mine.firebaseapp.com',
    storageBucket: 'time-of-mine.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9iqViy7pkCl0kesM4dVsh1p8izaQQPcI',
    appId: '1:1038026278537:android:430a3ed79f7dc66c336858',
    messagingSenderId: '1038026278537',
    projectId: 'time-of-mine',
    storageBucket: 'time-of-mine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcCR3QA13EUhHyqHphwCRpQsZ6KGAAZYE',
    appId: '1:1038026278537:ios:a37ca3ac6a6bb2bd336858',
    messagingSenderId: '1038026278537',
    projectId: 'time-of-mine',
    storageBucket: 'time-of-mine.firebasestorage.app',
    iosBundleId: 'com.example.timeOfMine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcCR3QA13EUhHyqHphwCRpQsZ6KGAAZYE',
    appId: '1:1038026278537:ios:a37ca3ac6a6bb2bd336858',
    messagingSenderId: '1038026278537',
    projectId: 'time-of-mine',
    storageBucket: 'time-of-mine.firebasestorage.app',
    iosBundleId: 'com.example.timeOfMine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFv3N0lybkZdlIH6XgXbJTo_qTrP_uRxk',
    appId: '1:1038026278537:web:9a229465a5c5d972336858',
    messagingSenderId: '1038026278537',
    projectId: 'time-of-mine',
    authDomain: 'time-of-mine.firebaseapp.com',
    storageBucket: 'time-of-mine.firebasestorage.app',
  );
}
